CREATE TABLE accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(20)    NOT NULL UNIQUE,
    holder_name    VARCHAR(80)    NOT NULL,
    balance        DECIMAL(15, 2) NOT NULL,
    currency       VARCHAR(3)     NOT NULL,
    pin_hash       VARCHAR(64)    NOT NULL
);

CREATE TABLE transfers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account VARCHAR(20)    NOT NULL,
    to_account   VARCHAR(20)    NOT NULL,
    amount       DECIMAL(15, 2) NOT NULL,
    fee          DECIMAL(15, 2) NOT NULL,
    reference    VARCHAR(20)    NOT NULL,
    note         VARCHAR(140),
    created_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);
